#!/bin/bash
# contract-sync — propagate gen-backend-v2 contract changes to every consumer.
#
# gen-backend-v2 owns the generated contracts (docs/generated/**, the creation
# card and model capability configs). Each consumer vendors a byte-identical
# copy or derives its own artifact from them, and each has a freshness gate that
# goes red while the copy is stale. When a watched backend path changes, this
# script runs the consumer's OWN regeneration command in a fresh shallow clone
# and opens a PR only when that regeneration produced a diff, so the change
# arrives without anyone filing a ticket for it.
#
# Guardrails that the unattended path must keep:
#   - generated artifacts are never hand-edited here; the consumer's own
#     generator produces the bytes.
#   - nothing is force-pushed. A branch for a backend sha that already has an
#     open PR is that PR, not a new one.
#   - a PR merges only when every newest-per-context status on its head is
#     success. Red, pending, or absent checks leave the PR open and log it.
#   - main's own push pipeline must be terminal before merging. Merging while
#     the pipeline for the previous main sha still runs cancels it and leaves
#     main without a verdict, which blocks every deploy gated on it (GEN-6025).
set -euo pipefail

# -----------------------------------------------------------------------------
# Configuration. Every value is overridable from the environment so the offline
# test can run this exact code against local bare repositories.
# -----------------------------------------------------------------------------

STATE_DIR="${CONTRACT_SYNC_STATE_DIR:-/var/lib/contract-sync}"
GITEA_URL="${GEN_GITEA_URL:-https://git.gen.pro}"
GITEA_OWNER="${CONTRACT_SYNC_OWNER:-GEN}"
GIT_BASE="${CONTRACT_SYNC_GIT_BASE:-$GITEA_URL}"
BACKEND_REPO="${CONTRACT_SYNC_BACKEND_REPO:-gen-backend-v2}"
BACKEND_BRANCH="${CONTRACT_SYNC_BACKEND_BRANCH:-main}"
CONSUMER_BRANCH="${CONTRACT_SYNC_CONSUMER_BRANCH:-main}"
BACKEND_URL="${CONTRACT_SYNC_BACKEND_URL:-$GIT_BASE/$GITEA_OWNER/$BACKEND_REPO.git}"
DRY_RUN="${DRY_RUN:-0}"

BRANCH_PREFIX="auto/contract-sync-"
LAST_BE_SHA_FILE="$STATE_DIR/last-be-sha"
LAST_BE_MANIFEST_FILE="$STATE_DIR/last-be-watched.tsv"
LOCK_FILE="$STATE_DIR/lock"
PRS_FILE="$STATE_DIR/.pulls.json"
STATUS_TMP_FILE="$STATE_DIR/.pull-statuses.json"
MANIFEST_TMP_FILE="$STATE_DIR/.watched-manifest.new"

CURL_TIMEOUT="${CONTRACT_SYNC_CURL_TIMEOUT:-30}"
GIT_TIMEOUT="${CONTRACT_SYNC_GIT_TIMEOUT:-300}"
REGEN_TIMEOUT="${CONTRACT_SYNC_REGEN_TIMEOUT:-600}"
AGENTIC_IMAGE="${CONTRACT_SYNC_AGENTIC_IMAGE:-git.gen.pro/gen/gen-agentic-ci:py311}"
STATUS_POLL_INTERVAL="${CONTRACT_SYNC_STATUS_POLL_INTERVAL:-20}"
STATUS_POLL_TIMEOUT="${CONTRACT_SYNC_STATUS_POLL_TIMEOUT:-900}"
MAIN_PIPELINE_WAIT="${CONTRACT_SYNC_MAIN_PIPELINE_WAIT:-180}"
COMMIT_NAME="${CONTRACT_SYNC_COMMIT_NAME:-contract-sync}"
COMMIT_EMAIL="${CONTRACT_SYNC_COMMIT_EMAIL:-contract-sync@gen.pro}"

# gen-backend-v2 paths whose change triggers a consumer sync. A change anywhere
# else (app code, tests) is not a contract change and must not open a PR.
WATCHED_PATHS=(
  "docs/generated"
  "config/creation_cards.yml"
  "config/model_capabilities.yml"
)

# gen-mcp-server regeneration, in this order. These are the vendor_*.py scripts
# whose upstream is gen-backend-v2: vendor_publish_platforms.py reads
# gen-backend-python and vendor_layer_prompts.py reads limitless-data, so a
# backend-v2 clone cannot run them and they are deliberately absent.
MCP_REGENERATE=(
  "scripts/vendor_creation_card_branches.py"
  "scripts/vendor_creation_card_matrix.py"
  "scripts/vendor_user_job_enums.py"
  "scripts/vendor_vidsheet_action_schema.py"
  "scripts/sync_model_capabilities.py"
)

# gen-agentic consumes these three artifacts byte-identically at
# src/gen/contracts/. Its freshness gate byte-compares the remote artifact, so
# copying the generated bytes is the whole regeneration step.
GEN_AGENTIC_ARTIFACTS=(
  "docs/generated/vidsheet-operations-schema.json"
  "docs/generated/vidsheet-semantic-draft-schema.json"
  "docs/generated/user-job-enums.json"
)

# Consumers, in the order they are processed. A repo is cloned from
# $GIT_BASE/$GITEA_OWNER/<name>.git and regenerated by the matching case arm in
# process_consumer(). CONTRACT_SYNC_CONSUMERS narrows the list for the offline
# test; it is space-separated.
CONSUMERS=(
  "gen-mcp-server"
  "gen-agentic"
  "limitless-fe"
  "api-docs"
)
if [ -n "${CONTRACT_SYNC_CONSUMERS:-}" ]; then
  read -r -a CONSUMERS <<<"$CONTRACT_SYNC_CONSUMERS"
fi

# git must fail fast without credentials instead of blocking a timer run on a
# prompt. git.gen.pro credentials come from the box's git credential helper, not
# from the API token, which is only for the API calls below.
export GIT_TERMINAL_PROMPT=0

# -----------------------------------------------------------------------------
# Logging. One line per event on stdout, which systemd forwards to journald.
# -----------------------------------------------------------------------------

log() {
  printf '%s contract-sync: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"
}

# -----------------------------------------------------------------------------
# Gitea API. The API token appears only as a curl header argument; its value is
# never printed, and the presence check below is the only other mention.
# -----------------------------------------------------------------------------

require_token() {
  [ -n "${GEN_GITEA_TOKEN:-}" ] || {
    log "ERROR: the Gitea API token is not set; refusing to push or open a PR"
    exit 2
  }
}

gitea_request() { # <method> <path> [payload-file] — response body on stdout
  local method="$1" path="$2" payload="${3:-}"
  if [ -n "$payload" ]; then
    curl -sS --max-time "$CURL_TIMEOUT" -X "$method" \
      -H "Authorization: token ${GEN_GITEA_TOKEN:-}" \
      -H "User-Agent: gen-contract-sync" \
      -H "Content-Type: application/json" \
      --data-binary "@$payload" \
      "$GITEA_URL/api/v1$path"
  else
    curl -sS --max-time "$CURL_TIMEOUT" -X "$method" \
      -H "Authorization: token ${GEN_GITEA_TOKEN:-}" \
      -H "User-Agent: gen-contract-sync" \
      "$GITEA_URL/api/v1$path"
  fi
}

gitea_status_code() { # <method> <path> [payload-file] — HTTP status on stdout
  local method="$1" path="$2" payload="${3:-}"
  if [ -n "$payload" ]; then
    curl -sS --max-time "$CURL_TIMEOUT" -o /dev/null -w '%{http_code}' -X "$method" \
      -H "Authorization: token ${GEN_GITEA_TOKEN:-}" \
      -H "User-Agent: gen-contract-sync" \
      -H "Content-Type: application/json" \
      --data-binary "@$payload" \
      "$GITEA_URL/api/v1$path" || true
  else
    curl -sS --max-time "$CURL_TIMEOUT" -o /dev/null -w '%{http_code}' -X "$method" \
      -H "Authorization: token ${GEN_GITEA_TOKEN:-}" \
      -H "User-Agent: gen-contract-sync" \
      "$GITEA_URL/api/v1$path" || true
  fi
}

# Print a scalar from a JSON file at a dotted path, or an empty line when absent.
json_scalar() { # <file> <dotted.path>
  python3 -c '
import json, sys
try:
    data = json.load(open(sys.argv[1]))
except (OSError, ValueError):
    print("")
    raise SystemExit(0)
for part in sys.argv[2].split("."):
    if isinstance(data, list):
        try:
            data = data[int(part)]
        except (IndexError, ValueError):
            data = None
    elif isinstance(data, dict):
        data = data.get(part)
    else:
        data = None
    if data is None:
        break
print("" if data is None or isinstance(data, (dict, list)) else data)
' "$1" "$2"
}

# Verdict for a Gitea statuses payload: the NEWEST row per context (by row id,
# never API order), restricted to a context prefix. Prints NONE, GREEN, RED:<cs>
# or PENDING:<cs>. Only a success counts as green; anything unrecognised is
# pending, so an unknown state can never be mistaken for a pass.
status_verdict() { # <statuses-file> <context-prefix>
  python3 -c '
import json, sys
try:
    rows = json.load(open(sys.argv[1]))
except (OSError, ValueError):
    print("PENDING:unreadable-statuses")
    raise SystemExit(0)
prefix = sys.argv[2]
newest = {}
for row in rows if isinstance(rows, list) else []:
    context = str(row.get("context") or "")
    if prefix and not context.startswith(prefix):
        continue
    if context not in newest or int(row.get("id") or 0) > int(newest[context].get("id") or 0):
        newest[context] = row
if not newest:
    print("NONE")
    raise SystemExit(0)
red = sorted(
    "%s:%s" % (c, r.get("status"))
    for c, r in newest.items()
    if r.get("status") in ("failure", "error", "warning")
)
pending = sorted(
    "%s:%s" % (c, r.get("status"))
    for c, r in newest.items()
    if r.get("status") not in ("success", "failure", "error", "warning")
)
if red:
    print("RED:" + ",".join(red))
elif pending:
    print("PENDING:" + ",".join(pending))
else:
    print("GREEN")
' "$1" "$2"
}

# -----------------------------------------------------------------------------
# git helpers
# -----------------------------------------------------------------------------

clone_repo() { # <url> <branch> <dir>
  local url="$1" branch="$2" dir="$3"
  case "$dir" in
    "$STATE_DIR"/*) ;;
    *)
      log "ERROR: refusing to refresh $dir outside $STATE_DIR"
      return 1
      ;;
  esac
  rm -rf -- "$dir"
  timeout "$GIT_TIMEOUT" git clone --quiet --depth 1 --branch "$branch" \
    --single-branch "$url" "$dir" || return 1
  # A shallow clone does not always publish the remote-tracking ref for the
  # branch it checked out. The consumer generators read the backend through
  # `git show origin/<branch>:<path>`, so make the ref exist explicitly.
  if ! git -C "$dir" show-ref --verify --quiet "refs/remotes/origin/$branch"; then
    git -C "$dir" update-ref "refs/remotes/origin/$branch" HEAD
  fi
  return 0
}

remote_backend_sha() {
  timeout "$GIT_TIMEOUT" git ls-remote "$BACKEND_URL" "refs/heads/$BACKEND_BRANCH" \
    | awk 'NR==1 {print $1}'
}

# "<blob-sha>\t<path>" for every watched file, sorted by git. Comparing this
# against the stored manifest answers "did a watched path change" without
# needing the previous commit's tree, which a depth-1 clone does not have.
watched_manifest() { # <backend-clone>
  git -C "$1" ls-tree -r HEAD -- "${WATCHED_PATHS[@]}" | awk '{print $3 "\t" $4}'
}

commit_message_file() { # <file> <subject> <backend-sha> <path...>
  local file="$1" subject="$2" sha="$3"
  shift 3
  {
    printf '%s\n\n' "$subject"
    printf 'Synced from gen-backend-v2 %s.\n\n' "$sha"
    printf '%s\n' "$@"
  } >"$file"
}

# Record the synced sha and the watched-file manifest together, each through a
# rename so a kill mid-write cannot leave a torn state file behind.
record_state() { # <backend-sha> <manifest-file>
  cp -f "$2" "$LAST_BE_MANIFEST_FILE.new"
  mv -f "$LAST_BE_MANIFEST_FILE.new" "$LAST_BE_MANIFEST_FILE"
  printf '%s\n' "$1" >"$LAST_BE_SHA_FILE.new"
  mv -f "$LAST_BE_SHA_FILE.new" "$LAST_BE_SHA_FILE"
}

# -----------------------------------------------------------------------------
# Per-consumer regeneration. Each function writes into the consumer clone with
# the repo's own generator; none of them edits an artifact by hand.
# -----------------------------------------------------------------------------

# These functions run inside a `|| rc=$?` list, where bash suppresses errexit
# for the whole function body. Every step that must stop the consumer has to
# check its own status explicitly.

regen_gen_mcp_server() { # <consumer-clone> <backend-clone>
  local clone="$1" backend="$2" script
  for script in "${MCP_REGENERATE[@]}"; do
    ( cd "$clone" && timeout "$REGEN_TIMEOUT" python3 "$script" \
        --backend-path "$backend" --ref "origin/$BACKEND_BRANCH" ) || return $?
  done
}

regen_gen_agentic() { # <consumer-clone> <backend-clone>
  local clone="$1" backend="$2" artifact dest
  for artifact in "${GEN_AGENTIC_ARTIFACTS[@]}"; do
    dest="$clone/src/gen/contracts/$(basename "$artifact")"
    mkdir -p "$(dirname "$dest")"
    [ -f "$backend/$artifact" ] || {
      log "gen-agentic: ERROR backend is missing $artifact"
      return 1
    }
    cp -- "$backend/$artifact" "$dest" || return 1
  done
  # The embedded MCP package's creation-cards.json is derived from gen.* modules
  # that read the contracts copied above, and a parity test byte-compares it, so
  # copying without rebuilding leaves the sync PR red. gen.* needs the project's
  # dependencies, which the CI image provides.
  [ -f "$clone/scripts/build_creation_card_artifact.py" ] || return 0
  timeout "$REGEN_TIMEOUT" docker run --rm --cpus 2 -v "$clone":/w -w /w \
    "$AGENTIC_IMAGE" sh -c 'pip install -q -e . >/dev/null 2>&1 &&
      PYTHONPATH=src python scripts/build_creation_card_artifact.py' || return $?
}

regen_limitless_fe() { # <consumer-clone> <backend-clone>
  local clone="$1" backend="$2"
  local artifact="src/schema/vidsheets/contracts/vidsheet-operations-schema.json"
  local sidecar="src/schema/vidsheets/contracts/vidsheet-operations-schema.source.json"
  local generated="src/schema/vidsheets/railsContract.generated.ts"
  if [ -f "$clone/scripts/sync-vidsheet-contract.mjs" ]; then
    # The repo's own generator so the artifact, its provenance sidecar and the
    # derived railsContract.generated.ts stay consistent. It stamps a fresh
    # vendoredAt on every run, so when the artifact bytes did not change there
    # is nothing to ship and those timestamp-only edits are reverted.
    ( cd "$clone" && GEN_BACKEND_PATH="$backend" timeout "$REGEN_TIMEOUT" \
        node scripts/sync-vidsheet-contract.mjs ) || return $?
    if git -C "$clone" diff --quiet -- "$artifact"; then
      git -C "$clone" checkout -- "$sidecar" "$generated" 2>/dev/null || true
    fi
  else
    mkdir -p "$(dirname "$clone/$artifact")"
    cp -- "$backend/docs/generated/vidsheet-operations-schema.json" "$clone/$artifact" || return 1
  fi
}

# 20 means "skip": the repo does not carry a regeneration command yet.
regen_api_docs() { # <consumer-clone> <backend-clone>
  local clone="$1" backend="$2"
  if [ ! -f "$clone/scripts/sync-from-backend.mjs" ]; then
    SKIP_REASON="scripts/sync-from-backend.mjs is not on $CONSUMER_BRANCH yet"
    return 20
  fi
  ( cd "$clone" && timeout "$REGEN_TIMEOUT" node scripts/sync-from-backend.mjs \
      --backend "$backend" )
}

# -----------------------------------------------------------------------------
# PR lifecycle
# -----------------------------------------------------------------------------

remote_branch_exists() { # <repo> <branch> — 0 yes, 1 no, 2 unknown
  local code
  code="$(gitea_status_code GET "/repos/$GITEA_OWNER/$1/branches/$2")"
  case "$code" in
    200) return 0 ;;
    404) return 1 ;;
    *) return 2 ;;
  esac
}

find_open_pr() { # <repo> <branch> — PR number or empty
  local repo="$1" branch="$2"
  gitea_request GET "/repos/$GITEA_OWNER/$repo/pulls?state=open&limit=50" >"$PRS_FILE" \
    || return 0
  python3 -c '
import json, sys
try:
    pulls = json.load(open(sys.argv[1]))
except (OSError, ValueError):
    print("")
    raise SystemExit(0)
for pull in pulls if isinstance(pulls, list) else []:
    if (pull.get("head") or {}).get("ref") == sys.argv[2]:
        print(pull.get("number"))
        break
else:
    print("")
' "$PRS_FILE" "$branch"
}

create_pr() { # <repo> <branch> <title> <body> — PR number or empty
  local repo="$1" branch="$2" title="$3" body="$4"
  local payload="$STATE_DIR/.pr-payload.json"
  python3 -c '
import json, sys
print(json.dumps({
    "head": sys.argv[1],
    "base": sys.argv[2],
    "title": sys.argv[3],
    "body": sys.argv[4],
}))
' "$branch" "$CONSUMER_BRANCH" "$title" "$body" >"$payload"
  gitea_request POST "/repos/$GITEA_OWNER/$repo/pulls" "$payload" >"$PRS_FILE" || return 0
  json_scalar "$PRS_FILE" "number"
}

# Poll a commit's statuses until every newest-per-context row is a success, a
# terminal failure, or the wait budget expires. With none_terminal=yes an empty
# status list is also an answer (a repo with no pipeline on that branch).
await_checks() { # <repo> <sha> <context-prefix> <max-wait-sec> <none-terminal>
  local repo="$1" sha="$2" prefix="$3" max_wait="$4" none_terminal="$5"
  local deadline verdict now
  deadline=$(( $(date +%s) + max_wait ))
  while :; do
    gitea_request GET "/repos/$GITEA_OWNER/$repo/commits/$sha/statuses?limit=50" \
      >"$STATUS_TMP_FILE" || true
    verdict="$(status_verdict "$STATUS_TMP_FILE" "$prefix")"
    case "$verdict" in
      GREEN | RED:* | PENDING:unreadable-statuses)
        printf '%s' "$verdict"
        return 0
        ;;
      NONE)
        if [ "$none_terminal" = "yes" ]; then
          printf '%s' "$verdict"
          return 0
        fi
        ;;
    esac
    now=$(date +%s)
    if [ "$now" -ge "$deadline" ]; then
      printf '%s' "$verdict"
      return 0
    fi
    sleep "$STATUS_POLL_INTERVAL"
  done
}

merge_pr() { # <repo> <number> <style> — HTTP status on stdout
  local repo="$1" number="$2" style="$3"
  local payload="$STATE_DIR/.merge-payload.json"
  printf '{"Do":"%s"}\n' "$style" >"$payload"
  gitea_status_code POST "/repos/$GITEA_OWNER/$repo/pulls/$number/merge" "$payload"
}

merge_when_green() { # <repo> <number> <head-sha> — 0 merged, 10 left open, 11 retry next tick, 1 error
  local repo="$1" number="$2" head_sha="$3"
  local verdict main_sha main_verdict tried style code

  # Only ci/woodpecker/* gates a merge, as in branch protection. Other contexts
  # (GitHub-Actions workflows no runner executes) stay pending forever.
  verdict="$(await_checks "$repo" "$head_sha" "ci/woodpecker/" "$STATUS_POLL_TIMEOUT" "no")"
  case "$verdict" in
    GREEN) ;;
    NONE)
      log "$repo: no check status for $head_sha yet; PR #$number is re-checked next tick"
      return 11
      ;;
    PENDING:*)
      log "$repo: checks still pending (${verdict#PENDING:}) after ${STATUS_POLL_TIMEOUT}s; PR #$number is re-checked next tick"
      return 11
      ;;
    RED:*)
      log "$repo: checks not green (${verdict#RED:}); leaving PR #$number open"
      return 10
      ;;
  esac

  # Merging cancels the pipeline running for main's current head when that repo
  # runs its pipeline with concurrency: 1, which leaves main with no verdict at
  # all. Wait for main's push contexts to settle first; a repo with none has
  # nothing to cancel.
  main_sha="$(json_scalar <(gitea_request GET "/repos/$GITEA_OWNER/$repo/branches/$CONSUMER_BRANCH" || true) "commit.id")"
  if [ -z "$main_sha" ]; then
    log "$repo: cannot read $CONSUMER_BRANCH head; leaving PR #$number open"
    return 10
  fi
  main_verdict="$(await_checks "$repo" "$main_sha" "ci/woodpecker/push/" "$MAIN_PIPELINE_WAIT" "yes")"
  case "$main_verdict" in
    GREEN | NONE) ;;
    *)
      log "$repo: $CONSUMER_BRANCH $main_sha push pipeline is ${main_verdict#*:}; PR #$number is re-checked next tick"
      return 11
      ;;
  esac

  tried=""
  for style in fast-forward-only rebase; do
    tried="${tried:+$tried,}$style"
    code="$(merge_pr "$repo" "$number" "$style")"
    if [ "$code" = "200" ]; then
      log "$repo: merged PR #$number ($style)"
      return 0
    fi
  done
  # A fast-forward-only repo refuses the merge once main has moved past the
  # sync branch. Rebase the PR onto main server-side; its pipeline re-runs and
  # the next tick re-checks and merges it.
  code="$(gitea_status_code POST "/repos/$GITEA_OWNER/$repo/pulls/$number/update?style=rebase")"
  if [ "$code" = "200" ]; then
    log "$repo: merge refused for PR #$number ($tried); rebased it onto $CONSUMER_BRANCH, re-checked next tick"
    return 11
  fi
  log "$repo: merge refused for PR #$number ($tried) and rebase onto $CONSUMER_BRANCH failed (HTTP $code); leaving it open"
  return 10
}

# -----------------------------------------------------------------------------
# One consumer: regenerate, and hand a diff off as a green-and-merged PR.
# Returns 0 (nothing to do / merged / skipped), 10 (PR left open for a human)
# or 1 (error, so the next tick retries instead of losing the change).
# -----------------------------------------------------------------------------

process_consumer() { # <name> <backend-sha> <backend-clone>
  local name="$1" backend_sha="$2" backend="$3"
  local clone="$STATE_DIR/$name"
  local url="$GIT_BASE/$GITEA_OWNER/$name.git"
  local branch="$BRANCH_PREFIX${backend_sha:0:8}"
  local title="chore: sync backend contracts to gen-backend-v2 ${backend_sha:0:8}"
  local regen_rc=0 pr_number="" head_sha="" body="" status_file
  local -a changed_paths=()
  local entry

  SKIP_REASON=""

  clone_repo "$url" "$CONSUMER_BRANCH" "$clone" || {
    log "$name: ERROR cannot clone $url"
    return 1
  }

  case "$name" in
    gen-mcp-server) regen_gen_mcp_server "$clone" "$backend" || regen_rc=$? ;;
    gen-agentic) regen_gen_agentic "$clone" "$backend" || regen_rc=$? ;;
    limitless-fe) regen_limitless_fe "$clone" "$backend" || regen_rc=$? ;;
    api-docs) regen_api_docs "$clone" "$backend" || regen_rc=$? ;;
    *)
      log "$name: ERROR no regeneration command is defined"
      return 1
      ;;
  esac

  if [ "$regen_rc" = "20" ]; then
    log "$name: skipped — $SKIP_REASON"
    return 0
  fi
  if [ "$regen_rc" != "0" ]; then
    log "$name: ERROR regeneration failed (exit $regen_rc)"
    return 1
  fi

  status_file="$STATE_DIR/.status.$name"
  if ! git -C "$clone" status --porcelain -z >"$status_file"; then
    log "$name: ERROR cannot read the working tree status"
    return 1
  fi
  while IFS= read -r -d '' entry; do
    changed_paths+=("${entry:3}")
  done <"$status_file"

  if [ "${#changed_paths[@]}" = "0" ]; then
    log "$name: no diff — vendored copies already current with ${backend_sha:0:8}"
    return 0
  fi

  if [ "$DRY_RUN" = "1" ]; then
    log "$name: ${#changed_paths[@]} file(s) changed — DRY_RUN plan: branch $branch, commit \"$title\", push, open PR, poll checks, merge (fast-forward-only then rebase); paths: ${changed_paths[*]}"
    return 0
  fi

  # A branch for this backend sha that already has an open PR is the previous
  # run's handoff. Never reuse a branch whose PR a human closed.
  local branch_rc=0
  remote_branch_exists "$name" "$branch" || branch_rc=$?
  if [ "$branch_rc" = "0" ]; then
    pr_number="$(find_open_pr "$name" "$branch")"
    if [ -n "$pr_number" ]; then
      head_sha="$(json_scalar <(gitea_request GET "/repos/$GITEA_OWNER/$name/branches/$branch" || true) "commit.id")"
      log "$name: PR #$pr_number is already open for ${backend_sha:0:8}; re-checking it"
      merge_when_green "$name" "$pr_number" "$head_sha"
      return $?
    fi
    log "$name: ERROR branch $branch exists with no open PR; refusing to reuse it"
    return 1
  elif [ "$branch_rc" = "2" ]; then
    log "$name: ERROR cannot read branch $branch from Gitea"
    return 1
  fi

  git -C "$clone" checkout -q -b "$branch" || {
    log "$name: ERROR cannot create branch $branch"
    return 1
  }
  git -C "$clone" add -- "${changed_paths[@]}" || {
    log "$name: ERROR cannot stage the regenerated files"
    return 1
  }
  commit_message_file "$STATE_DIR/.commit-msg.$name" "$title" "$backend_sha" "${changed_paths[@]}"
  git -C "$clone" -c user.name="$COMMIT_NAME" -c user.email="$COMMIT_EMAIL" \
    commit -q -F "$STATE_DIR/.commit-msg.$name" || {
    log "$name: ERROR cannot commit the regenerated files"
    return 1
  }
  head_sha="$(git -C "$clone" rev-parse HEAD)" || {
    log "$name: ERROR cannot read the new commit"
    return 1
  }

  if ! git -C "$clone" push --quiet origin "HEAD:refs/heads/$branch"; then
    log "$name: ERROR push of $branch failed"
    return 1
  fi

  pr_number="$(find_open_pr "$name" "$branch")"
  if [ -z "$pr_number" ]; then
    body="$(printf 'Synced from gen-backend-v2 %s.\n\nChanged paths:\n\n%s\n' \
      "$backend_sha" "${changed_paths[*]}")"
    pr_number="$(create_pr "$name" "$branch" "$title" "$body")"
  fi
  if [ -z "$pr_number" ]; then
    log "$name: ERROR $branch pushed but no PR could be opened"
    return 1
  fi

  log "$name: PR #$pr_number opened for $head_sha; waiting for checks"
  # A merge is the whole hand-off: gen-deployd deploys gen-mcp-server main to
  # staging and production (mcp.gen.pro) and every other consumer on its own.
  merge_when_green "$name" "$pr_number" "$head_sha"
}

# -----------------------------------------------------------------------------
# Run
# -----------------------------------------------------------------------------

for tool in git python3 curl flock; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "contract-sync: ERROR required tool not found: $tool" >&2
    exit 1
  }
done

mkdir -p "$STATE_DIR"

# One run at a time. A second timer tick that overlaps the first exits instead
# of cloning a second copy of every consumer.
exec 9>"$LOCK_FILE"
flock -n 9 || {
  log "another run holds $LOCK_FILE — skipping this tick"
  exit 0
}

if [ "$DRY_RUN" = "1" ]; then
  log "DRY_RUN=1: regeneration runs locally; no push, PR or merge"
else
  require_token
fi

backend_sha="$(remote_backend_sha || true)"
if [ -z "$backend_sha" ]; then
  log "ERROR cannot resolve $BACKEND_URL refs/heads/$BACKEND_BRANCH"
  exit 1
fi

last_sha=""
if [ -r "$LAST_BE_SHA_FILE" ]; then
  last_sha="$(cat "$LAST_BE_SHA_FILE")"
fi

if [ "$backend_sha" = "$last_sha" ]; then
  log "backend main ${backend_sha:0:8}: no backend change since the last sync"
  exit 0
fi

backend_clone="$STATE_DIR/$BACKEND_REPO"
if ! clone_repo "$BACKEND_URL" "$BACKEND_BRANCH" "$backend_clone"; then
  log "ERROR cannot clone $BACKEND_URL"
  exit 1
fi

# main can move between the ls-remote above and this clone. The clone's HEAD is
# what the artifacts actually come from, so the branch name, the commit message
# and the state file all name this sha, not the one resolved before the clone.
backend_sha="$(git -C "$backend_clone" rev-parse HEAD)"
if [ "$backend_sha" = "$last_sha" ]; then
  log "backend main ${backend_sha:0:8}: no backend change since the last sync"
  exit 0
fi

watched_manifest "$backend_clone" >"$MANIFEST_TMP_FILE"
watched_count="$(awk 'END {print NR+0}' "$MANIFEST_TMP_FILE")"

if [ -n "$last_sha" ] && [ -r "$LAST_BE_MANIFEST_FILE" ] \
  && cmp -s "$MANIFEST_TMP_FILE" "$LAST_BE_MANIFEST_FILE"; then
  # The backend moved but no watched artifact did: record the new sha so the
  # next tick does not re-diff it, and touch no consumer.
  log "backend main ${backend_sha:0:8}: $watched_count watched file(s), none changed since ${last_sha:0:8} — no consumer action"
  record_state "$backend_sha" "$MANIFEST_TMP_FILE"
  exit 0
fi

if [ -z "$last_sha" ]; then
  log "backend main ${backend_sha:0:8}: first run ($watched_count watched file(s)) — syncing every consumer"
else
  log "backend change ${last_sha:0:8}..${backend_sha:0:8}: $watched_count watched file(s)"
fi

failed=0
handed_off=0
retry=0
for name in "${CONSUMERS[@]}"; do
  rc=0
  process_consumer "$name" "$backend_sha" "$backend_clone" || rc=$?
  case "$rc" in
    0) ;;
    10) handed_off=1 ;;
    11) retry=1 ;;
    *) failed=1 ;;
  esac
done

# Advance only after every consumer reached a terminal disposition. A hard
# error leaves the state untouched so the next tick retries the same change
# instead of silently dropping it.
if [ "$failed" = "0" ] && [ "$retry" = "0" ]; then
  record_state "$backend_sha" "$MANIFEST_TMP_FILE"
  log "backend main ${backend_sha:0:8}: state advanced"
elif [ "$failed" = "0" ]; then
  log "backend main ${backend_sha:0:8}: a sync PR is still waiting on checks; state not advanced, the next tick re-checks it"
else
  log "backend main ${backend_sha:0:8}: a consumer errored; state not advanced, the next tick retries"
fi

if [ "$failed" != "0" ]; then
  exit 1
fi
if [ "$handed_off" != "0" ] || [ "$retry" != "0" ]; then
  exit 1
fi
exit 0
